openapi: 3.0.0
info:
  title: Todo, User & Gemini Chatbot API
  version: 1.0.0
  description: API quản lý Todo, User (đăng ký, đăng nhập, profile) và Chatbot Gemini AI

servers:
  - url: http://localhost:3000

paths:
  /api/user/register:
    post:
      summary: Đăng ký tài khoản
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Đăng ký thành công

  /api/user/login:
    post:
      summary: Đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Đăng nhập thành công, trả về token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /api/user/profile:
    get:
      summary: Lấy thông tin user (cần xác thực)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin user
        '401':
          description: Không có hoặc token không hợp lệ

  /api/todo:
    get:
      summary: Lấy danh sách Todo của user (cần xác thực)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Danh sách Todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Tạo mới một Todo (cần xác thực)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '201':
          description: Tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /api/todo/{id}:
    get:
      summary: Lấy thông tin một Todo theo id (cần xác thực)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thông tin Todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Không tìm thấy Todo
    put:
      summary: Cập nhật một Todo theo id (cần xác thực)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Không tìm thấy Todo
    delete:
      summary: Xóa một Todo theo id (cần xác thực)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Xóa thành công
        '404':
          description: Không tìm thấy Todo

  /api/chatbot:
    post:
      summary: Gửi câu hỏi tới Gemini Chatbot (cần xác thực)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      responses:
        '200':
          description: Phản hồi từ Gemini Chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: string
        '401':
          description: Không có hoặc token không hợp lệ

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Todo:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        user:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    TodoInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
      required:
        - title